export const VALID_CODES = [
  "A9K3Q7",
  "M2F8RZ",
  "7TQ4L9",
  "X5N8C2",
  "R4Z7M1",
  "K9W2F8",
  "3C7AQL",
  "N8X2M5",
  "F6RZ9K",
  "Q4T1W7",
  "8MZK3A",
  "L5R9X2",
  "C7F4NQ",
  "W2A8MZ",
  "9T3KXR",
  "FZ6Q1M",
  "A4N7W8",
  "2XK9RC",
  "M7Q5FZ",
  "K1T8A4",
  "R9C6X2",
  "W7M4FQ",
  "XK2Z93",
  "NQ5A8R",
  "4Z9TMW",
  "C1X7F8",
  "QZ3M2K",
  "A8R5N9",
  "T4FZ1C",
  "M9WQX7",
];

export const CODE_TO_VERSION: { [key: string]: number } = {
  A9K3Q7: 1,
  M2F8RZ: 2,
  "7TQ4L9": 3,
  X5N8C2: 4,
  R4Z7M1: 5,
  K9W2F8: 6,
  "3C7AQL": 7,
  N8X2M5: 8,
  F6RZ9K: 9,
  Q4T1W7: 10,
  "8MZK3A": 11,
  L5R9X2: 12,
  C7F4NQ: 13,
  W2A8MZ: 14,
  "9T3KXR": 15,
  FZ6Q1M: 16,
  A4N7W8: 17,
  "2XK9RC": 18,
  M7Q5FZ: 19,
  K1T8A4: 20,
  R9C6X2: 21,
  W7M4FQ: 22,
  XK2Z93: 23,
  NQ5A8R: 24,
  "4Z9TMW": 25,
  C1X7F8: 26,
  QZ3M2K: 27,
  A8R5N9: 28,
  T4FZ1C: 29,
  M9WQX7: 30,
};

export const FLOWCHART_GROUPS: { [key: string]: string[] } = {
  general_medicine: [
    "Feeling Generally Ill Flowchart",
    "Unexplained Weight Loss Flowchart",
    "Overweight Flowchart",
    "Fever Flowchart",
    "Fever In Young Children Flowchart",
    "Fever In Children Flowchart",
    "Excessive Sweating Flowchart",
    "Slow Weight Gain In Young Children Flowchart",
  ],
  neurology: [
    "Feeling Faint And Fainting Flowchart",
    "Dizziness Flowchart",
    "Headache Flowchart",
    "Numbness Or Tingling Flowchart",
    "Twitching And Trembling Flowchart",
    "Pain In The Face Flowchart",
    "Confusion Flowchart",
    "Confusion In Older People Flowchart",
    "Impaired Memory Flowchart",
    "Difficulty Speaking Flowchart",
  ],
  mental_behavioral_health: [
    "Disturbing Thoughts Or Feelings Flowchart",
    "Unusual Behavior Flowchart",
    "Depression Flowchart",
    "Anxiety Flowchart",
    "Hallucinations Flowchart",
    "Nightmares Flowchart",
    "Difficulty Sleeping Flowchart",
    "Waking At Night In Children Flowchart",
    "Crying In Infants Flowchart",
  ],
  dermatology: [
    "Hair Loss Flowchart",
    "General Skin Problems Flowchart",
    "Facial Skin Problems Flowchart",
    "Itchy Spots And Rashes Flowchart",
    "Itching Without A Rash Flowchart",
    "Rash With Fever Flowchart",
    "Raised Spots And Lumps Flowchart",
    "Abnormal Hair Growth In Women Flowchart",
    "Skin Problems In Young Children Flowchart",
    "Itching In Children Flowchart",
    "Swellings In Children Flowchart",
    "Swellings Under The Skin Flowchart",
  ],
  eye_ent_oral_health: [
    "Painful Eye Flowchart",
    "Disturbed Or Impaired Vision Flowchart",
    "Earache Flowchart",
    "Noises In The Ear Flowchart",
  ],
  gastroenterology: [
    "Vomiting Flowchart",
    "Recurring Vomiting Flowchart",
    "Abdominal Pain Flowchart",
    "Recurring Abdominal Pain Flowchart",
    "Swollen Abdomen Flowchart",
    "Gas And Belching Flowchart",
    "Diarrhea Flowchart",
    "Constipation Flowchart",
    "Abnormal Looking Stools Flowchart",
    "Vomiting In Infants Flowchart",
    "Diarrhea In Infants Flowchart",
    "Abdominal Pain In Children Flowchart",
  ],
  musculoskeletal_system: [
    "Backache Flowchart",
    "Cramp Flowchart",
    "Painful Or Stiff Neck Flowchart",
    "Painful Arm Or Hand Flowchart",
    "Painful Leg Flowchart",
    "Painful Knee Flowchart",
    "Painful Shoulder Flowchart",
    "Painful Ankles Flowchart",
    "Swollen Ankles Flowchart",
    "Foot Problems Flowchart",
    "Limping In Children Flowchart",
  ],
  reproductive_health: [
    "Painful Or Enlarged Testicles Flowchart",
    "Painful Intercourse In Men Flowchart",
    "Infertility In Men Flowchart",
    "Infertility In Women Flowchart",
    "Absent Periods Flowchart",
    "Heavy Periods Flowchart",
    "Painful Periods Flowchart",
    "Pelvic Pain In Women Flowchart",
    "Irregular Vaginal Bleeding Flowchart",
    "Abnormal Vaginal Discharge Flowchart",
  ],
};
